import { useMemo, useState } from 'react';
import { Link, Plus, Save, Search } from 'lucide-react';
import { addCanvasChild, addStockToCanvasNode, collectBranchStocks, createCanvasSharePayload, getBranchMetrics, parseCanvasSharePayload, renameCanvasNode, type CanvasNode, type IndustryCanvas } from '../data/industryCanvas';
import { searchSecuritySuggestions, type SecuritySuggestion } from '../data/priceDiscipline';

export function IndustryCanvasEditor({ canvas, onChange, onSave, onStock, onBranch }: { canvas: IndustryCanvas; onChange: (canvas: IndustryCanvas) => void; onSave: (canvas: IndustryCanvas) => void; onStock?: (code: string, name: string) => void; onBranch?: (node: CanvasNode, method: 'equal' | 'marketCap') => void }) {
  const [selectedId, setSelectedId] = useState(canvas.root.id);
  const [query, setQuery] = useState('');
  const [suggestions, setSuggestions] = useState<SecuritySuggestion[]>([]);
  const [shareInput, setShareInput] = useState('');
  const [weightMethod, setWeightMethod] = useState<'equal' | 'marketCap'>('equal');
  const selected = useMemo(() => findNode(canvas.root, selectedId) ?? canvas.root, [canvas, selectedId]);
  const metrics = getBranchMetrics(selected);
  const refreshSuggestions = async (value: string) => { setQuery(value); setSuggestions(value.trim() ? await searchSecuritySuggestions(value).catch(() => []) : []); };
  const addSuggestion = (item: SecuritySuggestion) => { onChange(addStockToCanvasNode(canvas, selected.id, { ...item, change: null, marketCap: null, pe: null })); setSuggestions([]); setQuery(''); };
  const importShare = () => { const imported = parseCanvasSharePayload(shareInput); if (imported) { onChange(imported); setSelectedId(imported.root.id); setShareInput(''); } };
  const marketCapReady = collectBranchStocks(selected).every((stock) => (stock.marketCap ?? 0) > 0);
  return <section className="industry-canvas-editor"><header><div><span>我的产业链</span><h3>{canvas.name}</h3><small>预览指标按去重公司计算；PE 仅纳入正值与有效值。</small></div><div><button type="button" onClick={() => navigator.clipboard?.writeText(createCanvasSharePayload(canvas, window.location.href).value)}><Link size={15} />分享</button><button type="button" onClick={() => onSave(canvas)}><Save size={15} />保存</button></div></header><div className="industry-canvas-editor__body"><div className="industry-canvas-outline"><CanvasOutline node={canvas.root} selectedId={selected.id} onSelect={setSelectedId} /><button type="button" onClick={() => { const id = crypto.randomUUID(); onChange(addCanvasChild(canvas, selected.id, { id, name: '新细分环节' })); setSelectedId(id); }}><Plus size={15} />添加下级</button></div><div className="industry-canvas-inspector"><label>环节名称<input value={selected.name} onChange={(event) => onChange(renameCanvasNode(canvas, selected.id, event.target.value))} /></label><div className="industry-canvas-metrics"><span>平均涨幅 <b>{metrics.averageChange === null ? '—' : `${metrics.averageChange.toFixed(2)}%`}</b></span><span>平均 PE <b>{metrics.averagePe === null ? '—' : metrics.averagePe.toFixed(2)} <small>{metrics.peCompanyCount} / {metrics.companyCount}</small></b></span><span>平均市值 <b>{metrics.averageMarketCap === null ? '—' : metrics.averageMarketCap.toFixed(0)}</b></span></div><div className="industry-canvas-search"><Search size={15} /><input value={query} onChange={(event) => refreshSuggestions(event.target.value)} placeholder="搜索股票并一键加入" />{suggestions.map((item) => <button type="button" key={item.code} onClick={() => addSuggestion(item)}>{item.name} <small>{item.code}</small><Plus size={14} /></button>)}</div><div className="industry-canvas-stocks">{selected.stocks.map((stock) => <button type="button" key={stock.code} onClick={() => onStock?.(stock.code, stock.name)}>{stock.name}<small>{stock.code}</small></button>)}</div><div className="industry-canvas-preview"><span>临时预览</span><button type="button" className={weightMethod === 'equal' ? 'is-active' : ''} onClick={() => setWeightMethod('equal')}>等权</button><button type="button" disabled={!marketCapReady} className={weightMethod === 'marketCap' ? 'is-active' : ''} onClick={() => setWeightMethod('marketCap')}>市值加权</button><small>{marketCapReady ? '保存后可在自定义指数中进一步调整权重。' : '市值缺失时不能使用市值加权。'}</small><button type="button" onClick={() => { if (window.confirm('确认将当前预览保存为自定义指数吗？')) onBranch?.(selected, weightMethod); }}>确认保存并打开自定义指数</button></div><div className="industry-canvas-import"><input value={shareInput} onChange={(event) => setShareInput(event.target.value)} placeholder="粘贴分享链接或 JSON" /><button type="button" onClick={importShare}>加载链接</button></div></div></div></section>;
}

function findNode(node: CanvasNode, id: string): CanvasNode | null { if (node.id === id) return node; for (const child of node.children) { const found = findNode(child, id); if (found) return found; } return null; }
function CanvasOutline({ node, selectedId, onSelect }: { node: CanvasNode; selectedId: string; onSelect: (id: string) => void }) { return <ul><li><button type="button" className={selectedId === node.id ? 'is-active' : ''} onClick={() => onSelect(node.id)}>{node.name}<small>{collectBranchStocks(node).length} 家</small></button>{node.children.length ? <ul>{node.children.map((child) => <CanvasOutline key={child.id} node={child} selectedId={selectedId} onSelect={onSelect} />)}</ul> : null}</li></ul>; }
